/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactSubmission {
  'name' : string,
  'email' : string,
  'website' : string,
  'message' : string,
  'restaurantName' : string,
  'timestamp' : Time,
}
export interface PortfolioEntry {
  'id' : bigint,
  'resultMetric' : string,
  'imageDescription' : string,
  'restaurantName' : string,
  'category' : string,
}
export interface Service {
  'id' : bigint,
  'title' : string,
  'description' : string,
  'iconName' : string,
}
export interface Testimonial {
  'id' : bigint,
  'authorName' : string,
  'quote' : string,
  'restaurantName' : string,
  'avatarInitial' : string,
}
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addPortfolioEntry' : ActorMethod<[string, string, string, string], bigint>,
  'addService' : ActorMethod<[string, string, string], bigint>,
  'addTestimonial' : ActorMethod<[string, string, string, string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deletePortfolioEntry' : ActorMethod<[bigint], undefined>,
  'deleteService' : ActorMethod<[bigint], undefined>,
  'deleteTestimonial' : ActorMethod<[bigint], undefined>,
  'getAllContactSubmissions' : ActorMethod<[], Array<ContactSubmission>>,
  'getAllPortfolioEntries' : ActorMethod<[], Array<PortfolioEntry>>,
  'getAllServices' : ActorMethod<[], Array<Service>>,
  'getAllTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPortfolioEntriesByCategory' : ActorMethod<
    [string],
    Array<PortfolioEntry>
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'submitContactForm' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
  'updatePortfolioEntry' : ActorMethod<
    [bigint, string, string, string, string],
    undefined
  >,
  'updateService' : ActorMethod<[bigint, string, string, string], undefined>,
  'updateTestimonial' : ActorMethod<
    [bigint, string, string, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];